---
booktitle: Proceedings of The 27th Conference on Learning Theory
volume: 35
year: '2014'
shortname: COLT
start: 2014-06-13
end: 2014-06-15
published: 2014-05-29
sections:
- name: preface
  title: Preface
- name: default
  title: Regular Papers
- name: open
  title: Open Problems
layout: proceedings
series: Proceedings of Machine Learning Research
id: COLT-2014
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
editor:
- given: Maria Florina
  family: Balcan
- given: Vitaly
  family: Feldman
- given: Csaba
  family: Szepesvári
description: |
  Proceedings of The 27th Conference on Learning Theory
    Held in Barcelona, Spain on 13-15 June 2014

  Published as Volume 35 by the Proceedings of Machine Learning Research on 29 May 2014.

  Volume Edited by:
    Maria Florina Balcan
    Vitaly Feldman
    Csaba Szepesvári

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 13--15 Jun
url: http://proceedings.mlr.press
baseurl: "/v35"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v35
bibtex_copy: true
email: ''
conference:
  name: Conference on Learning Theory
  url: https://orfe.princeton.edu/conferences/colt2014/
  location: Barcelona, Spain
  dates:
  - 2014-06-13
  - 2014-06-14
  - 2014-06-15
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v35.bib
