---
booktitle: Proceedings of The 27th Conference on Learning Theory
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
volume: 35
year: '2014'
shortname: COLT
start: 2014-06-13
end: 2014-06-15
published: 2014-05-29
sections:
- name: preface
  title: Preface
- name: default
  title: Regular Papers
- name: open
  title: Open Problems
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: COLT-2014
month: 0
cycles: false
editor:
- given: Maria Florina
  family: Balcan
- given: Vitaly
  family: Feldman
- given: Csaba
  family: Szepesvári
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 27th Conference on Learning Theory
    Held in Barcelona, Spain on 13-15 June 2014

  Published as Volume 35 by the Proceedings of Machine Learning Research on 29 May 2014.

  Volume Edited by:
    Maria Florina Balcan
    Vitaly Feldman
    Csaba Szepesvári

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 13--15 Jun
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v35"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v35
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Conference on Learning Theory
  url: https://orfe.princeton.edu/conferences/colt2014/
  location: Barcelona, Spain
  dates:
  - 2014-06-13
  - 2014-06-14
  - 2014-06-15
  number: 27
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
